# Generated by Django 3.1.1 on 2020-11-21 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20201103_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidos',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
